version: '3.8'

services:
  # PG Admin
  sms.pgadmin:
    image: dpage/pgadmin4
    container_name: sms_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=software@treeshake.com.au
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - '6060:80'
    networks:
      - sms_network

  # Postgres
  sms.db:
    image: postgres:16.4
    container_name: sms_db
    environment:
      - TZ=Australia/Sydney
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sms_db
    ports:
      - "5431:5432"
    restart: always
    networks:
      - sms_network

  # Webapp
  sms.webapp:
    container_name: sms_webapp
    build:
      context: .
      dockerfile: Dockerfile

    # Set environment variables directly in the compose file
    # environment:
      # ENV_VARIABLE: ${ENV_VARIABLE}
      # NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 4012:4012
    networks:
      - sms_network
    depends_on:
      - sms.db

#network section
networks:
  sms_network:
    name: sms_network
    driver: bridge
  default:
    name: sms_network